openapi: 3.1.0
info:
  title: AdoptMe API
  version: 1.0.0
  description: API para gestionar usuarios, mascotas y adopciones
paths:
  /adoptions:
    get:
      summary: Obtener todas las adopciones
      description: Devuelve una lista de todas las adopciones realizadas en el sistema.
      operationId: getAllAdoptions
      responses:
        '200':
          description: Lista de adopciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Adoption'
  /adoptions/{uid}/{pid}:
    post:
      summary: Crear una adopción
      description: Crea una adopción entre un usuario y una mascota.
      operationId: createAdoption
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario
          schema:
            type: string
            example: "60d21b4667d0d8992e610c84"  # Valor mock para uid
        - name: pid
          in: path
          required: true
          description: ID de la mascota
          schema:
            type: string
            example: "60d21b4667d0d8992e610c85"  # Valor mock para pid
      responses:
        '201':
          description: Adopción creada exitosamente
        '404':
          description: Usuario o mascota no encontrada
  /adoptions/{uid}/{aid}:
    get:
      summary: Obtener detalles de una adopción
      description: Obtiene los detalles de una adopción específica realizada por un usuario.
      operationId: getAdoption
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario (propietario de la adopción)
          schema:
            type: string
            example: "60d21b4667d0d8992e610c82"  # Valor mock para uid
        - name: aid
          in: path
          required: true
          description: ID de la adopción
          schema:
            type: string
            example: "60d21b4667d0d8992e610c81"  # Valor mock para aid
      responses:
        '200':
          description: Detalles de la adopción
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adoption'
        '404':
          description: Adopción no encontrada
components:
  schemas:
    Adoption:
      type: object
      required:
        - owner
        - pet
      properties:
        owner:
          type: string
          description: ID del propietario (usuario)
        pet:
          type: string
          description: ID de la mascota adoptada
